# Generated by Django 4.1.7 on 2023-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hos_app', '0002_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_image',
            field=models.ImageField(default=1, upload_to='department'),
            preserve_default=False,
        ),
    ]
