# Generated by Django 4.1.7 on 2023-04-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hos_app', '0006_comment_delete_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
